language: java

sudo: required

before_install: cd backend

after_success:
- bash <(curl -s https://codecov.io/bash)
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- ./mvnw clean install -Dspring.profiles.active=ci -DskipTests=true -Dmaven.javadoc.skip=true -B -V



