language: java

sudo: required

jdk:
    - oraclejdk8
    
before_install: cd backend

after_success:
- bash <(curl -s https://codecov.io/bash)
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

script: mvn install

